// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1jp1-9T1jxm0Eu6eMiCHSdWE5IGvsoQ4',
    appId: '1:442530434893:web:552cb1ff919e4c93c3b104',
    messagingSenderId: '442530434893',
    projectId: 'vehicle-doc-intelligence',
    authDomain: 'vehicle-doc-intelligence.firebaseapp.com',
    storageBucket: 'vehicle-doc-intelligence.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgPCpaGu7RCaCvULSN2RTBiToer5jK5Zo',
    appId: '1:442530434893:android:97985ce223ff8d0ac3b104',
    messagingSenderId: '442530434893',
    projectId: 'vehicle-doc-intelligence',
    storageBucket: 'vehicle-doc-intelligence.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuURkv3z-CQHF62xlQ_FDiA8W3BeBI7iA',
    appId: '1:442530434893:ios:9da01354bb53bc27c3b104',
    messagingSenderId: '442530434893',
    projectId: 'vehicle-doc-intelligence',
    storageBucket: 'vehicle-doc-intelligence.firebasestorage.app',
    iosBundleId: 'com.example.vehicleAiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuURkv3z-CQHF62xlQ_FDiA8W3BeBI7iA',
    appId: '1:442530434893:ios:9da01354bb53bc27c3b104',
    messagingSenderId: '442530434893',
    projectId: 'vehicle-doc-intelligence',
    storageBucket: 'vehicle-doc-intelligence.firebasestorage.app',
    iosBundleId: 'com.example.vehicleAiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1jp1-9T1jxm0Eu6eMiCHSdWE5IGvsoQ4',
    appId: '1:442530434893:web:b1940b1945b72d89c3b104',
    messagingSenderId: '442530434893',
    projectId: 'vehicle-doc-intelligence',
    authDomain: 'vehicle-doc-intelligence.firebaseapp.com',
    storageBucket: 'vehicle-doc-intelligence.firebasestorage.app',
  );

}